services:
  ollama:
    image: ollama/ollama:0.6.2
    container_name: ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_LLM_LIBRARY=cuda
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./entrypoint.sh:/root/entrypoint.sh
      - ./Modelfile:/root/Modelfile
      - ollama:/root/.ollama
    entrypoint: ["/root/entrypoint.sh"]
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - internal

  chat_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chat
    restart: unless-stopped
    ports:
      - '7860:7860'
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - internal



volumes:
 ollama: {}

networks:
  internal:
    driver: bridge